"""Add missed name column to DB

Revision ID: f3ef5ebd9874
Revises: 820861205352
Create Date: 2026-04-09 03:01:17.382322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ef5ebd9874'
down_revision: Union[str, Sequence[str], None] = '820861205352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city', 'name')
    # ### end Alembic commands ###
